import type { Config } from "tailwindcss";

export default {
    darkMode: ["class"],
    content: ["./index.html", "./src/**/*.{ts,tsx}"],
    theme: {
        extend: {
            fontFamily: {
                sans: ["'Geist'", "'Inter'", "system-ui", "sans-serif"],
                mono: ["'Geist Mono'", "'JetBrains Mono'", "monospace"],
                display: ["'Cal Sans'", "'Geist'", "sans-serif"],
            },
            colors: {
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
                popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
                primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
                secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
                muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
                accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
                destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                sidebar: "hsl(var(--sidebar))",
                "sidebar-foreground": "hsl(var(--sidebar-foreground))",
                "sidebar-border": "hsl(var(--sidebar-border))",
                "sidebar-accent": "hsl(var(--sidebar-accent))",
                "preview-bg": "hsl(var(--preview-bg))",
                "chat-user": "hsl(var(--chat-user))",
                "chat-ai": "hsl(var(--chat-ai))",
                "code-bg": "hsl(var(--code-bg))",
                "token-purple": "hsl(var(--token-purple))",
                "token-blue": "hsl(var(--token-blue))",
                "token-green": "hsl(var(--token-green))",
                "token-orange": "hsl(var(--token-orange))",
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
                xl: "calc(var(--radius) + 4px)",
                "2xl": "calc(var(--radius) + 8px)",
            },
            keyframes: {
                "fade-in": { from: { opacity: "0", transform: "translateY(4px)" }, to: { opacity: "1", transform: "translateY(0)" } },
                "slide-in-left": { from: { opacity: "0", transform: "translateX(-8px)" }, to: { opacity: "1", transform: "translateX(0)" } },
                "slide-in-right": { from: { opacity: "0", transform: "translateX(8px)" }, to: { opacity: "1", transform: "translateX(0)" } },
                "pulse-dot": { "0%,100%": { opacity: "1" }, "50%": { opacity: "0.3" } },
                shimmer: { from: { backgroundPosition: "200% 0" }, to: { backgroundPosition: "-200% 0" } },
                "spin-slow": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
                "cursor-blink": { "0%,100%": { opacity: "1" }, "50%": { opacity: "0" } },
            },
            animation: {
                "fade-in": "fade-in 0.2s ease-out",
                "slide-in-left": "slide-in-left 0.2s ease-out",
                "slide-in-right": "slide-in-right 0.2s ease-out",
                "pulse-dot": "pulse-dot 1.4s ease-in-out infinite",
                shimmer: "shimmer 2s linear infinite",
                "spin-slow": "spin-slow 3s linear infinite",
                "cursor-blink": "cursor-blink 1s ease-in-out infinite",
            },
            backgroundImage: {
                "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
                "noise": "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.05'/%3E%3C/svg%3E\")",
            },
            boxShadow: {
                "glow-primary": "0 0 20px hsl(var(--primary) / 0.25)",
                "glow-sm": "0 0 10px hsl(var(--primary) / 0.15)",
                "inner-border": "inset 0 1px 0 0 hsl(var(--border))",
            },
        },
    },
    plugins: [],
} satisfies Config;